version: '3.7'

services:
  twitter-clone-backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
      # Pass arguments to specified dockerfile.
      args:
        - user_id=$UID
        - group_id=$GID
        - user=$USER
    # Map port 3000 (first) on local machine to port 3000 (second) inside the container.
    ports:
      - "3000:3000"
    # Those services will start first.
    volumes:
      - .:/app
    depends_on:
      - twitter-clone-pg-dev
      - twitter-clone-pg-test
    # `links` allows referencing services by their names (e.g. `pgdev`) instead of ip addresses.
    links:
      - twitter-clone-pg-dev
      - twitter-clone-pg-test
    working_dir: /app
    command: yarn start-dev

  twitter-clone-pg-dev:
    image: library/postgres:13.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  twitter-clone-pg-test:
    image: library/postgres:13.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
