version: '3.7'

services:
  twitter-clone-backend:
    container_name: twitter-clone-backend
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        - user_id=$UID
        - group_id=$GID
        - user=$USER
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - twitter-clone-pg-dev
      - twitter-clone-pg-test
    links:
      - twitter-clone-pg-dev
      - twitter-clone-pg-test
    working_dir: /app
    command: yarn start-dev

  twitter-clone-pg-dev:
    container_name: twitter-clone-pg-dev
    image: library/postgres:13.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: twitter-clone-pg-dev
        target: /var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  twitter-clone-pg-test:
    container_name: twitter-clone-pg-test
    image: library/postgres:13.4-alpine
    ports:
      - "5433:5432"
    volumes:
      - type: volume
        source: twitter-clone-pg-test
        target: /var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  twitter-clone-pg-dev:
  twitter-clone-pg-test:
